### PR TITLE
Added default options to script initialization

### PR DESCRIPTION
**Pull request by pablovilas**
Added options:

debug: To avoid displaying info in console if you want to
samples: Sometimes is not important that +-ms so maybe 3 - 5 samples it's ok.
url: If you minimize and concat your js this option avoids returning the hole script, you can define a custom url in your server that returns nothing or whatever you want.

Thanks

### CODE REVIEW

**Comment by NodeGuy** [comment]
Thank you for the pull request.

* I don't want a separate `ServerDateConfig` object.  We'll just put the options into `ServerDate`.
* Let's set `debug` to `false` by default.
* I don't see reducing the number of samples taken by 5 - 7 as significant enough to warrant a new configuration setting.
* Rather than allowing a custom URL, let's perform a `HEAD` request instead of a `GET` to lower the request cost.

**Comment by pablovilas** [comment]
Perfect, thanks. Please feel free to close the pr.

**Comment by NodeGuy** [comment]
Meaning what—are you agreeing or disagreeing?

**Comment by pablovilas** [comment]
I'm agree with you. But I'll leave an option for samples, but it's up to you :).
Thanks.

**Comment by NodeGuy** [comment]
In that case please update the pull request with my suggested changes.

**Comment by pablovilas** [comment]
I'll close this pr and open a new one with the suggested changes

**Pull request closed without merging**
